# Camera Parameters (Compatible with op3_ball_detector usb_cam configuration)
/**:
    ros__parameters:
      video_device: "/dev/video0"
      framerate: 30.0
      io_method: "mmap"
      frame_id: "cam_link"
      pixel_format: "mjpeg2rgb"  # see usb_cam/supported_formats for list of supported formats
      av_device_format: "YUV422P"
      image_width: 1280
      image_height: 720
      camera_name: "camera"
      brightness: 128
      contrast: 128
      saturation: 128
      sharpness: 128
      gain: 0
      white_balance_automatic: false
      white_balance_temperature: 4000
      auto_exposure: false
      exposure_time_absolute: 250
